#! /bin/sh

/usr/libexec/polkit-gnome-authentication-agent-1 &

sxhkd &

dbus-launch xfce4-panel &

blueman-applet &

xfce4-power-manager  &

nm-applet &

picom &

nitrogen --restore &

xfsettingsd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           2
bspc config top_padding          17
bspc config right_padding        0
bspc config left_padding         0
bspc config bottom_padding       0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifer mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
